targets:
  ubuntu-16.04:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/hooks/postinst
